### PR TITLE
Add yml file and improve usability for small datasets

### PR DESCRIPTION
**Pull request by aspitarl**
I have added more details in the commit messages, but reproducing here: 

1) I have created a environment.yml file that can be used to create a anaconda environment in which the main notebook will run in jupyterlab. This includes the correct bokeh version (1.3.4) and the scispacy model dataset. 

2) I removed the cell that installs the scispacy model. I also added a cell that allows for reduction of the json database, so that the notebook can run quickly on a reduced dataset. 

You may or may not want to incorporate either of these changes, but I wanted to share.

### CODE REVIEW

**Comment by MaksimEkin** [comment]
@aspitarl Thank you very much for your contribution. I am reviewing the pull request.

**How could we handle `prefix: C:\Users\aspit\anaconda3\envs\nlp` in the yml file to allow it to be used among different systems?** This looks like the yml file has the Windows directory tree under your user. It is a great idea to include this as yml instead of downloading the scispacy module within the Notebook. This also helps to make sure all would have the correct Bokeh version which is 1.3.4.

We would want to have the Notebook ran on all the dataset, rather than only including 1000 instances. Analyzing all dataset allows us to see how well our approach generalizes, as well as allowing the models to see more instances to learn better.

**Comment by aspitarl** [comment]
Good catch. I just learned how to make yml files today, so bear with me. [Reading up](https://stackoverflow.com/questions/49174185/export-conda-environment-without-prefix-variable-which-shows-local-path-to-execu) on it it doesn't look like the prefix matters. I've removed that line and tested that it will create and environment that will run the notebook. 

I am aware that we want to have the model use as large of a dataset as possible. The processing steps were taking forever on my computer so I added parameter 'number_entries' when 'all_json' is loaded to specify a number of articles to reduce the size to, but if this parameter is set to None, then that reduction doesn't happen. Perhaps it could be set to None by default.

**Comment by MaksimEkin** [comment]
@aspitarl Thank you for making the fix on yml file. Let me also review how the yml files are used and get back to you. I have never used it before. Also, thank you for sharing the resource link for yml file.

If you would like to test the Notebook fast on a smaller dataset, I recommend taking a random sample of the data; such that, the instances will be trained in a better representation of the population. Taking first n instances may cause results that would be very different than the actual.

Using the [sample function of pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html), you can take a random sample of the population, dataset. You could add the following code before [cell 14 (**Take a Look at the Data** section)](https://maksimekin.github.io/COVID19-Literature-Clustering/COVID19_literature_clustering.html#Take-a-Look-at-the-Data:) 

`df_covid_sample = df_covid.sample(n=1000, random_state=42)`
_Going forward, use df_covid_sample instead of df_covid in the Notebook._

Here, n will be the number of instances that you want, number of articles. And random_state will determine the, well, random state 😄 Setting the random state will allow reproducible results, you will get the same random sample each time. 

Taking the random sample after dropping null values will allow your random sample to only include the articles with valid parameters. 

Finally, if you are concerned about ram and don't want to hold the old DataFrame but just have the random sample, do the below sampling where we replace df_covid instead: 

`df_covid = df_covid.sample(n=1000, random_state=42)`

**Comment by aspitarl** [comment]
I would check out [this](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) page regarding yml files. 

Thinking about it more, it is probably better to just to more of a standard requirements.txt or setup.py. I was motivated to create the yml file as I wanted to create a 'nlp' conda environment for  working with a colleauge.

My computer was actually taking a long time loading the data into a dataframe, hence why I wanted to reduce the 'all_json' file. You may be intending for this to run on powerful computers, though.

**Comment by MaksimEkin** [comment]
@aspitarl Maybe then we could take a [random sample from the list](https://pynative.com/python-random-sample/) of directories?

```python
import random

all_json = random.sample(all_json, 1000)
```

That is a very good idea to use a standard requirements.txt. Thank you for your recommendation. Do you already have one? If so, your contribution would be very helpful. Otherwise, we should be able to put together that file.

Thanks again!

**Pull request closed without merging**
